services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Development.dockerfile
    container_name: todo-frontend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NUXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - backend
    networks:
      - todo-network
    command: npm run dev

  backend:
    build:
      context: .
      dockerfile: docker/backend/Development.dockerfile
    container_name: todo-backend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:password@db:3306/todo_db
    depends_on:
      - db
    networks:
      - todo-network
    command: npm run dev

  db:
    image: mysql:8.0
    container_name: todo-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  mysql-data:
