version: '3.8'
services:
  frontend:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - NUXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
      - NUXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    depends_on:
      - supabase
    command: yarn dev

  supabase:
    image: supabase/postgres:15.1
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: todo_app
    ports:
      - '5432:5432'
    volumes:
      - supabase-data:/var/lib/postgresql/data

volumes:
  supabase-data:
