version: '3.8'
services:
  # フロントエンドサービス
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - NUXT_PUBLIC_API_BASE_URL=http://localhost:3001
    env_file:
      - .env
    depends_on:
      backend:
        condition: service_started
    networks:
      - app-network

  # バックエンドサービス
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - NUXT_PUBLIC_SUPABASE_URL=${NUXT_PUBLIC_SUPABASE_URL}
      - NUXT_PUBLIC_SUPABASE_KEY=${NUXT_PUBLIC_SUPABASE_KEY}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_started
    networks:
      - app-network

  # データベースサービス
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: todo_app
    ports:
      - '5432:5432'
    volumes:
      - ./server/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
